package com.mewsic.app.scanner

import java.io.File
import java.util.Locale

object SongClassifier {

    // Common voice recording, messaging, system, and speech directory fragments
    private val EXCLUDED_PATH_KEYWORDS = listOf(
        "whatsapp",
        "voice notes",
        "voicenotes",
        "voice recorder",
        "voicerecorder",
        "soundrecorder",
        "sound_recorder",
        "call_rec",
        "call recording",
        "callrecordings",
        "call recorder",
        "recordings",
        "recorder",
        "voicememo",
        "voice_memo",
        "telegram audio",
        "telegram audio",
        "notifications",
        "ringtones",
        "alarms",
        "audiobooks",
        "podcasts",
        ".trash",
        "cache",
        "system"
    )

    // Regex patterns for filenames generated by voice recorders, whatsapp, call recorders
    private val RECORDING_NAME_PATTERNS = listOf(
        Regex("(?i)^AUD-\\d{8}-WA\\d+.*"),                     // WhatsApp Audio
        Regex("(?i)^PTT-\\d{8}-WA\\d+.*"),                     // WhatsApp Voice Note
        Regex("(?i)^(REC|RECORD|VOICE)[_\\s\\-]?\\d+.*"),     // Generic Voice Recorders
        Regex("(?i)^Audio[_\\s\\-]?\\d{8}[_\\s\\-]?\\d{6}.*"), // Date-stamped audio
        Regex("(?i)^\\d{8}[_\\s\\-]\\d{6}.*"),                 // e.g. 20240315_142305
        Regex("(?i)^Call[_\\s\\-@].*"),                        // Call recording
        Regex("(?i).*(call[\\s_\\-]?recording|voice[\\s_\\-]?memo|sound[\\s_\\-]?recorder).*")
    )

    private val SUSPICIOUS_ARTIST_NAMES = listOf(
        "<unknown>", "unknown", "unknown artist", "samsung", "xiaomi", "huawei", "oppo", "vivo",
        "voice recorder", "sound recorder", "recorder", "call recorder"
    )

    /**
     * Determines whether an audio file is likely a genuine music song or a voice recording / sound clip.
     *
     * @param title Title metadata
     * @param artist Artist metadata
     * @param album Album metadata
     * @param durationMs Duration in milliseconds
     * @param filePath Absolute path or display name
     * @param isMusicFlag MediaStore IS_MUSIC column value
     * @return Pair(isSong: Boolean, confidence: Float)
     */
    fun classifyAudio(
        title: String,
        artist: String,
        album: String,
        durationMs: Long,
        filePath: String,
        isMusicFlag: Boolean
    ): Boolean {
        val cleanPath = filePath.lowercase(Locale.ROOT).replace(File.separatorChar, '/')
        val cleanTitle = title.trim()
        val cleanArtist = artist.trim().lowercase(Locale.ROOT)
        val cleanAlbum = album.trim().lowercase(Locale.ROOT)

        // 1. HARD EXCLUSION: Too short (under 25 seconds is overwhelmingly a notification, UI sound, ringtone, or voice memo)
        if (durationMs < 25_000) {
            return false
        }

        // 2. HARD EXCLUSION: Excluded directories (WhatsApp, Recordings, Call logs, System)
        for (keyword in EXCLUDED_PATH_KEYWORDS) {
            if (cleanPath.contains(keyword)) {
                return false
            }
        }

        // 3. HARD EXCLUSION: Known voice recorder filename patterns
        val fileName = cleanPath.substringAfterLast('/')
        for (pattern in RECORDING_NAME_PATTERNS) {
            if (pattern.matches(fileName) || pattern.matches(cleanTitle)) {
                return false
            }
        }

        // 4. HARD EXCLUSION: Voice note audio formats (AMR, 3GP) unless clearly tagged with artist
        val extension = cleanPath.substringAfterLast('.', "")
        if ((extension == "amr" || extension == "3gp" || extension == "awb") && isSuspiciousArtist(cleanArtist)) {
            return false
        }

        // 5. HARD EXCLUSION: Extremely long audio (> 45 mins) with no artist/album is almost certainly a recorded lecture/meeting
        if (durationMs > 2_700_000 && isSuspiciousArtist(cleanArtist) && isSuspiciousAlbum(cleanAlbum)) {
            return false
        }

        // 6. SCORING SYSTEM for ambiguous items
        var score = 0.0f

        // MediaStore music flag
        if (isMusicFlag) score += 0.25f

        // High quality artist tag
        if (!isSuspiciousArtist(cleanArtist)) {
            score += 0.35f
        }

        // High quality album tag
        if (!isSuspiciousAlbum(cleanAlbum)) {
            score += 0.25f
        }

        // Typical song duration (1m30s to 12 mins)
        if (durationMs in 90_000..720_000) {
            score += 0.20f
        }

        // Path indicator (Music, Downloads, Songs, Albums)
        if (cleanPath.contains("/music/") || cleanPath.contains("/download/") || cleanPath.contains("/songs/")) {
            score += 0.20f
        }

        // Title looks like a song title (doesn't have file extension or purely underscores)
        if (!cleanTitle.endsWith(".mp3", ignoreCase = true) && !cleanTitle.endsWith(".m4a", ignoreCase = true)) {
            score += 0.10f
        }

        return score >= 0.40f
    }

    private fun isSuspiciousArtist(artist: String): Boolean {
        if (artist.isBlank()) return true
        return SUSPICIOUS_ARTIST_NAMES.any { artist.contains(it) }
    }

    private fun isSuspiciousAlbum(album: String): Boolean {
        if (album.isBlank()) return true
        return SUSPICIOUS_ARTIST_NAMES.any { album.contains(it) }
    }
}
